<?php

/**
 * Implementation of hook_form_alter
 *
 */
function su_it_services_form_alter(&$form, $form_state, $form_id) {

  /*
   *  Once enabled this module cannot be disabled (unless you get to the database or use Drush)
   *  So evil.
   */

  if ($form_id == 'system_modules') {
    unset($form['status']['#options']['su_it_services']);
  }

  /*
   *  Disable file directory path and temp directory changes. These are set during installation
   *  and should not be changed.
   *
   */
  if ($form_id == 'system_file_system_settings') {
    unset($form['file_directory_path']);
    unset($form['file_directory_temp']);
  }
}

