<?php

/**
 * Implements hook_form_alter().
 *
 */

function su_it_services_form_alter(&$form, $form_state, $form_id) {

  // Once enabled this module cannot be disabled (unless you get to the database or use Drush)
  // So evil.
  // Drush is run through the cli so we don't act if that's the interface being used
  if (($form_id == 'system_modules') &&   (php_sapi_name() != 'cli')) {
    unset($form['modules']['Stanford']['su_it_services']['enable']);
  }

  // Disable file directory path and temp directory changes. These are set during installation
  // and should not be changed.

  if ($form_id == 'system_file_system_settings') {
    unset($form['file_public_path']);
    unset($form['file_private_path']);
    unset($form['file_temporary_path']);
  }

  // We store the department names here instead of the database so that when new themes
  // are released, or older ones are retired, there is only one place that needs to be
  // updated.

  $department_themes = array('stanfordmodern');

  // act if this is the theme page and department themes are disabled

/*
 * Department Themes
 * We will have to implement this differently, due to the way that D7 handles themes
 */
/*  if (($form_id == 'system_themes_admin_form') && !(variable_get('su_department_themes', 0))) {

    // Disable the enable and default buttons for each department theme
    foreach ($department_themes as $theme) {
      unset($form['status']['#options'][$theme]);
      unset($form['theme_default']['#options'][$theme]);
    }
  }

  // act if this is the admin theme page and department themes are disabled

  if (($form_id == 'system_admin_theme_settings') && !(variable_get('su_department_themes', 0))) {

    // Remove the department theme as an option for the administration theme
    foreach ($department_themes as $theme) {
      unset($form['admin_theme']['#options'][$theme]);
    }
  }*/
}
