<?php
// $Id$

/**
 * @file
 * The install file; creates and deletes any needed variables
 *
 */

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function su_it_services_install() {
  variable_set('su_department_themes', 0);
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function su_it_services_uninstall() {
  variable_del('su_department_themes');
}
